### ISSUE TITLE
Steno keyboard layer

### ISSUE THREAD

**Issue by Sillabix** [enzocoralc/Tiny20#1]
Hi, this keyboard is very interesting. As noted  by @pekudzu on the Plover server on Discord it seems perfect to use as a stenographic device with the Michela system (which has just 20 keys), in particular with the Midi4Text theory to write words syllabically. Have you ever thought about adding a "steno" layer? 

https://github.com/Sillabix/Midi4Text

**Comment by enzocoralc** [comment]
Hello, thanks!
For the firmware, it can use ZMK, QMK or KMK (as well as circuitpython) so you can customize the keymap at your liking. I haven't worked with plover, does it need anything special?

**Comment by Sillabix** [comment]
Yes, QMK should work with Plover (several keyboards which are Plover
compatibile use that firmware).

Moreover I was wondering if the promicro would be capable to translate
directly the keys combination list in syllables. This would be nice because
with an orthographic system like Midi4Text would be possible to write
syllabically directly from the keyboard without using Plover.

Il ven 23 set 2022, 12:16 Lorenzo ***@***.***> ha scritto:
